{
  "blocks": [
    {
      "alwaysDisplay": true,
      "blockID": "eac6abfa-52d2-4d94-b018-332c2bfab1da",
      "group": 0,
      "instanceID": "100378d5-3319-4a6b-80f8-146a62452870",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    },
    {
      "alwaysDisplay": true,
      "blockID": "3764474b-0663-49d4-b143-429dedb9cf9d",
      "group": 0,
      "instanceID": "0b66636d-3255-4595-a912-3407c78c72b2",
      "traitConditions": 0,
      "traits": [],
      "useTraits": false
    }
  ],
  "id": "579a3be6-bb44-46e0-abdb-c076d4383b80",
  "name": "ExampleNewspaper-DefaultBlock"
}