name: Build and Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set build tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Copy Content
      run: cp -R AdditionalContent DDSLoader/AdditionalContent
    - name: Archive Files
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: "DDSLoader-${{ steps.vars.outputs.sha_short }}.zip"
        path: 'DDSLoader'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "DDSLoader-${{ steps.vars.outputs.sha_short }}.zip"
        token: ${{ secrets.TOKEN }}
        makeLatest: true
        allowUpdates: true
        tag: "DDSLoader-${{ steps.vars.outputs.sha_short }}"
