name: Build and Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy Content
      run: cp -R AdditionalContent DDSLoader/AdditionalContent
    - name: Archive Files
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        path: 'DDSLoader'
    - name: Set release tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip"
        token: ${{ secrets.TOKEN }}
        makeLatest: true
        allowUpdates: true
        tag: ${{ steps.vars.outputs.sha_short }}
